config/routes.rb
Rails.application.routes.draw do
  resources :items
  root "items#index"
  resources :cities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
require 'net/http'
class City < ApplicationRecord
  # geocode_by_city_and_state :address => :city_state
  geocoded_by :name, if: :name_changed?

  after_validation :geocode, if: ->(obj){ obj.name.present? and obj.name_changed? }

  validates :name, presence: true, uniqueness: true


  def weather_data
    Rails.cache.fetch("#{cache_key_with_version}/weather_data", expires_in: 12.hours) do
      url = "https://api.openweathermap.org/data/2.5/weather?lat=#{self.latitude}&lon=#{self.longitude}&units=imperial&appid=2d29671ab8b2ba1d5c84be1d9f943c35"
      uri = URI(url)
      response = Net::HTTP.get_response(uri)
      JSON.parse(response.body)
    end
  end




end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
  # before_action :set_cities

  # def set_cities
  #   @Los_Angeles = 
  #   cities = [
      
  #   ]
  # end
  private 

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]
  protect_from_forgery with: :null_session, only: [:create, :update, :destroy]
  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name, :weather, :description, :longitude, :latitude)
    end
end

app/controllers/items_controller.rb
# require 'uri'
require 'net/http'

class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  protect_from_forgery with: :null_session, only: [:create]

  # GET /items or /items.json
  def index    
    @items = Item.all
    

  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :quantity, :city_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <p>
    <strong>Name:</strong>
    <%= city.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= city.description %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= city.latitude %>
  </p>
  <p>
    <strong>Longitude:</strong>
    <%= city.longitude %>
  </p>

</div>
<br>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Show this city", @city %> |
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cities</h1>

<div id="items">
  <table id="customers">
    <tr>
      <th>Name</th>
      <th>Weather</th>
      <th>items</th>
    </tr>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td>  
          <img src="http://openweathermap.org/img/wn/<%#= item.city.weather_data['weather'].first['icon'] %>@2x.png" alt="">
          <%= city.weather_data['weather'].first["main"] %> 
          <%= city.weather_data['main']["temp"] %>
        </td>
        <td><%= link_to "Show", city %></td>
      </tr>

    <% end %>
  </table>
</div>
<br>
<%= link_to "New city", new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @city %> 

<div>
  <%= link_to "Edit this city", edit_city_path(@city) %> |
  <%= link_to "Back to cities", cities_path %>

  <%= button_to "Destroy this city", @city, method: :delete %>
</div>

<br>
<br>
<br>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>


  <br>
  <div>
    <%= form.label :city_id, style: "display: block" %>
    <%= form.collection_select :city_id, City.order(:name), :id, :name %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Item:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Location City Current Weather:</strong> <br>
    <%= item.city.weather_data['weather'].first["main"] %> <br>
    <%= item.city.weather_data['main']["temp"] %> F
  </p>

  <p>
    <strong>Total Items:</strong>
    <%= item.quantity %>
  </p>



</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h3 class="header">Inventorable</h3>
<div id="items">
  <table id="customers">
    <tr>
      <th>Item Name</th>
      <th>Description</th>
      <th>City</th>
      <th>Weather Description</th>
      <th>links</th>
    </tr>
    <% @items.each do |item| %>
      <%# <% cache item do %> 
        <tr>
          <td><%= item.name %></td>
          <td><%= item.description %></td>
          <td><%= link_to item.city.name, city_path(item) %></td>
          <td>  
            <%= item.city.weather_data['weather'].first["main"] %> 
            <%= item.city.weather_data['main']["temp"] %> F
          </td>
          <td> <div class="small"> <%= link_to "Show", item %> || <%= link_to "Edit", edit_item_path(item) %> || <%= link_to "Destroy", item_path(item), :method => :delete  %> </div> </td>
        </tr>
      <%# <% end %>
    <% end %>
  </table>
</div>
<br>
<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit", edit_item_path(@item) %> |
  <%= link_to "Back", items_path %>
  <br> <br>
  <%= button_to "Destroy", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="container">
      <nav class="">
        <div class="">
         <Span class="navbar"><%= link_to "View Items", items_path %></Span> 
         <Span class="navbar"> <%= link_to "View Cities", cities_path %></Span> 
         <Span class="navbar"> <%= link_to "Add New Inventory Items", new_item_path %></Span>
         <Span class="navbar"> <%= link_to "Add New Cities", new_city_path %></Span>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>